version: "3"

services:
  backend:
    build:
      context: ./backend_e-weather
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend_e-weather/:/app
    working_dir: /app
    command: sh run.sh
    expose:
      - 8000
    env_file:
      - ./settings/.env

  nginx:
    build: ./nginx
    ports:
      - 80:8080
    depends_on:
      - backend
